// Builds a local, data-free replica of the LIVE public schema from the
// read-only catalog snapshot (live_snapshot_2026-09-29.json): tables,
// defaults, constraints, indexes, the REAL function bodies (incl.
// get_top_matches), triggers, RLS flags, policies, table/column grants and
// function ACLs — plus minimal Supabase auth/storage scaffolding.
//
// Differences from live, on purpose:
//   - the `matches-push-notification` webhook trigger is not created (its
//     body calls supabase_functions.http_request with a service key; it is
//     redacted in the snapshot and irrelevant to access control);
//   - auth.* and storage.* are minimal stand-ins with Supabase's semantics
//     for auth.uid()/auth.role() and storage.foldername() (real body).
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const here = path.dirname(fileURLToPath(import.meta.url));
export const snapshot = JSON.parse(
  fs.readFileSync(path.join(here, 'live_snapshot_2026-09-29.json'), 'utf8'),
);

const rows = snapshot.schema;
const of = (k) => rows.filter((r) => r.k === k);

function scaffold() {
  return `
create role anon nologin noinherit;
create role authenticated nologin noinherit;
create role service_role nologin noinherit bypassrls;
create role authenticator login noinherit;
grant anon, authenticated, service_role to authenticator;

create schema auth;
create table auth.users (id uuid primary key, email text, email_confirmed_at timestamptz);
create function auth.uid() returns uuid language sql stable as $$
  select nullif(coalesce(current_setting('request.jwt.claim.sub', true),
    (nullif(current_setting('request.jwt.claims', true), '')::jsonb ->> 'sub')), '')::uuid $$;
create function auth.role() returns text language sql stable as $$
  select nullif(coalesce(current_setting('request.jwt.claim.role', true),
    (nullif(current_setting('request.jwt.claims', true), '')::jsonb ->> 'role')), '')::text $$;
create function auth.jwt() returns jsonb language sql stable as $$
  select coalesce(nullif(current_setting('request.jwt.claims', true), '')::jsonb, '{}'::jsonb) $$;
grant usage on schema auth to anon, authenticated, service_role;
grant execute on all functions in schema auth to anon, authenticated, service_role;

create schema storage;
create table storage.buckets (id text primary key, name text not null, public boolean default false,
  file_size_limit bigint, allowed_mime_types text[]);
create table storage.objects (
  id uuid primary key default gen_random_uuid(),
  bucket_id text references storage.buckets(id),
  name text not null,
  owner uuid,
  created_at timestamptz default now(),
  unique (bucket_id, name));
alter table storage.objects enable row level security;
grant usage on schema storage to anon, authenticated, service_role;
grant select, insert, update, delete on storage.objects to anon, authenticated, service_role;
grant select on storage.buckets to anon, authenticated, service_role;

grant usage on schema public to anon, authenticated, service_role;
create sequence public.waitlist_number_seq;
grant usage, select on sequence public.waitlist_number_seq to anon, authenticated, service_role;
`;
}

function tables() {
  const byTable = new Map();
  for (const c of of('col')) {
    const v = JSON.parse(c.v);
    if (!byTable.has(c.t)) byTable.set(c.t, []);
    byTable.get(c.t).push({ name: c.n, ...v });
  }
  let sql = '';
  for (const [t, cols] of byTable) {
    cols.sort((a, b) => a.pos - b.pos);
    const defs = cols.map((c) => {
      let d = `"${c.name}" ${c.type}`;
      if (c.identity === 'a') d += ' generated always as identity';
      if (c.identity === 'd') d += ' generated by default as identity';
      if (c.default) d += ` default ${c.default}`;
      if (c.notnull) d += ' not null';
      return d;
    });
    sql += `create table public.${t} (\n  ${defs.join(',\n  ')}\n);\n`;
  }
  return sql;
}

function constraints() {
  const cons = of('con');
  const conNames = new Set(cons.map((c) => c.n));
  // Primary/unique/check first, then FKs (tables all exist by now).
  const order = (d) => (d.startsWith('FOREIGN') ? 1 : 0);
  let sql = '';
  for (const c of [...cons].sort((a, b) => order(a.v) - order(b.v))) {
    sql += `alter table public.${c.t} add constraint "${c.n}" ${c.v};\n`;
  }
  for (const i of of('idx')) {
    if (conNames.has(i.n)) continue; // created by the constraint
    sql += `${i.v};\n`;
  }
  return sql;
}

function functionAcl(name, acl) {
  // acl like "=X/postgres postgres=X/postgres anon=X/postgres …"
  let sql = '';
  const sig = snapshot.functions.find((f) => f.name === name);
  const header = sig.def.match(/FUNCTION (public\.[a-z_]+\([^)]*\))/);
  const argTypes = header[1]
    .replace(/^public\.[a-z_]+\(/, '')
    .replace(/\)$/, '')
    .split(',')
    .map((a) => a.trim())
    .filter(Boolean)
    .map((a) => a.replace(/ DEFAULT .*/i, '').split(' ').slice(1).join(' '));
  const ref = `public.${name}(${argTypes.join(', ')})`;
  sql += `revoke all on function ${ref} from public, anon, authenticated, service_role;\n`;
  for (const entry of acl.split(' ').filter(Boolean)) {
    const [grantee, rest] = entry.split('=');
    if (!rest || !rest.includes('X')) continue;
    if (grantee === 'postgres') continue;
    sql += `grant execute on function ${ref} to ${grantee === '' ? 'public' : grantee};\n`;
  }
  return sql;
}

function functions(target) {
  let sql = '';
  for (const f of snapshot.functions) {
    // A real Supabase project already has storage.foldername & co.
    if (f.kind === 'storagefn' && target === 'supabase') continue;
    sql += `${f.def};\n`;
  }
  for (const f of snapshot.functions) {
    if (f.kind === 'fn') sql += functionAcl(f.name, f.acl);
  }
  if (target !== 'supabase') {
    sql += 'grant execute on function storage.foldername(text) to anon, authenticated, service_role;\n';
  }
  return sql;
}

function triggers() {
  let sql = '';
  for (const t of of('trg')) {
    if (t.v === 'WEBHOOK_REDACTED') continue;
    sql += `${t.v};\n`;
  }
  return sql;
}

function security(target) {
  let sql = '';
  if (target === 'supabase') {
    // Start from exactly the live grants, not the new project's defaults.
    const tables = [...new Set(of('col').map((c) => c.t))];
    for (const t of tables) sql += `revoke all on public.${t} from anon, authenticated;\n`;
    for (const p of of('pol')) sql += `drop policy if exists "${p.n}" on ${p.t};\n`;
  }
  for (const r of of('rls')) {
    if (r.n === 'true') sql += `alter table public.${r.t} enable row level security;\n`;
    if (r.v === 'true') sql += `alter table public.${r.t} force row level security;\n`;
  }
  for (const p of of('pol')) {
    const v = JSON.parse(p.v);
    const [schema, table] = p.t.split('.');
    const roles = v.roles.join(', ');
    let s = `create policy "${p.n}" on ${schema}.${table} as ${v.permissive.toLowerCase()} for ${v.cmd.toLowerCase()} to ${roles}`;
    if (v.qual) s += ` using (${v.qual})`;
    if (v.check) s += ` with check (${v.check})`;
    sql += `${s};\n`;
  }
  // Table grants exactly as live (information_schema.role_table_grants).
  for (const g of of('grant')) {
    const privs = g.v.split(',').join(', ');
    sql += `grant ${privs} on public.${g.t} to ${g.n};\n`;
  }
  // profiles: authenticated's live column-level UPDATE allowlist.
  const upd = snapshot.profile_column_privileges_authenticated
    .filter((c) => c.privs.includes('UPDATE'))
    .map((c) => `"${c.column}"`);
  sql += `grant update (${upd.join(', ')}) on public.profiles to authenticated;\n`;
  sql += 'grant all on all tables in schema public to service_role;\n';
  for (const b of of('bucket')) {
    sql += `insert into storage.buckets (id, name, public) values ('${b.t}', '${b.t}', ${b.n}) on conflict (id) do update set public = excluded.public;\n`;
  }
  if (target === 'supabase') {
    // Realtime: live publishes public.messages (chat).
    sql += `do $$ begin
  if not exists (select 1 from pg_publication_tables where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'messages') then
    alter publication supabase_realtime add table public.messages;
  end if;
end $$;\n`;
  }
  return sql;
}

/** Minimal stand-in for what a fresh Supabase project already provides
 * (roles, auth.uid(), storage schema + helpers, realtime publication) — used
 * only to prove the 'supabase' target SQL loads and the packages apply on it. */
export function supabasePlatformStandIn() {
  const storageFns = snapshot.functions.filter((f) => f.kind === 'storagefn').map((f) => `${f.def};`);
  return [scaffold().replace(/create sequence public\.waitlist_number_seq;\n.*\n/, ''), ...storageFns,
    'create publication supabase_realtime;'].join('\n');
}

/**
 * target 'pglite'   — full stand-alone replica incl. minimal auth/storage (tests).
 * target 'supabase' — sanitized schema for a FRESH Supabase test project:
 *   no roles/auth/storage scaffolding (the platform has them), exact live
 *   grants/policies, no webhook trigger (no live URL or key), no cron jobs,
 *   no data. Wrapped in one transaction.
 */
export function buildReplicaSql({ target = 'pglite' } = {}) {
  if (target === 'supabase') {
    return [
      '-- Generated by supabase/proposed/tests/replica.mjs (target=supabase) from',
      `-- ${snapshot.captured_at} live catalog snapshot. Schema only, no data, no secrets.`,
      'begin;',
      'create sequence if not exists public.waitlist_number_seq;',
      'grant usage, select on sequence public.waitlist_number_seq to authenticated, service_role;',
      tables(),
      constraints(),
      functions(target),
      triggers(),
      security(target),
      'commit;',
    ].join('\n');
  }
  return [scaffold(), tables(), constraints(), functions(target), triggers(), security(target)].join('\n');
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  const target = process.argv.includes('--target=supabase') ? 'supabase' : 'pglite';
  process.stdout.write(buildReplicaSql({ target }));
}
